### ISSUE TITLE
[iOS] Incompatible with Xcode 9.3

### ISSUE THREAD

**Issue by kirillplatonov** [lazaronixon/react-native-turbolinks#11]
First of all - thanks for this wonderful library.

I updated Xcode to 9.3 recently (around 20 March). And can't compile app anymore. I receive this error:
```
Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1: /Users/kirillplatonov/Code/react-native-turbolinks/ios/Turbolinks.framework/Modules/Turbolinks.swiftmodule/x86_64.swiftmodule
```

Do you know how to fix it? Looks like it's `turbolinks-ios` problem. Maybe there is a simple way to recompile turbolinks framework with latest swift version?

**Comment by kirillplatonov** [comment]
I tried to install toolchain for swift 4.0.3. With it it will compile but fail on runtime with the following error:
```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/kirillplatonov/Library/Developer/CoreSimulator/Devices/C6AB7A3C-2D2A-482A-A70C-95DFFD07818F/data/Containers/Bundle/Application/97B1061B-DD01-4A65-951A-99BCA3AB8AEA/Traintool.app/Frameworks/Turbolinks.framework/Turbolinks
  Reason: Incompatible library version: Turbolinks requires version 1.0.0 or later, but libswiftCore.dylib provides version 0.0.0
(lldb) 
```

**Comment by lazaronixon** [comment]
Thank you.. I will check it

**Comment by lazaronixon** [comment]
Fixed https://github.com/lazaronixon/react-native-turbolinks/releases/tag/v1.3.4
I only recompiled Turbolinks.framework with new xcode 9.3
