### ISSUE TITLE
Turbolinks.visitTabBar causes issues with the app

### ISSUE THREAD

**Issue by scottharvey** [lazaronixon/react-native-turbolinks#12]
I'm having issues getting a tab bar to work, I have the example app running using the example server. Inside the componentDidMount function in App.js I've added this line

`Turbolinks.visitTabBar([{tabTitle: 'Home', url: Constants.baseUrl}])`

When I launch the app on IOS it only partially functions, here's a gif showing the issue.

![screen](https://user-images.githubusercontent.com/78157/38249666-a4f932d8-3776-11e8-895a-9528505c4370.gif)

I don't see any errors or warnings in the console when I have that running either.

**Comment by scottharvey** [comment]
Quick follow up, I can see the requests are hitting the demo server when I click those links so maybe it's the app not processing the request.

**Comment by lazaronixon** [comment]
Try remove Turbolinks.Visit.. use only visitTabBar...

**Comment by scottharvey** [comment]
That seems to have fixed it 😄 

I can't believe I tried so many things but didn't see that.

Thanks for the awesome library, it's saved me hours of work. 👍
