### ISSUE TITLE
Unable to run Example app on iOS

### ISSUE THREAD

**Issue by nconroy** [lazaronixon/react-native-turbolinks#13]
### Is this a bug report?

Yes

### Environment
react-native: 0.55.2
iOS 11.3 on simulator

### Steps to Reproduce

Follow the steps for running the demo
One additional step to run npm install inside the Example folder
demo-server is running and I can visit it on http://localhost:9292
I have changed the constants.js file to http://localhost:9292
react-native run-ios

### Expected Behavior

Should see demo app running

### Actual Behavior
Error Json value 
Type NSMutableDictionary cannot be converted to NSArray

<img width="426" alt="screen shot 2018-04-17 at 6 28 16 pm" src="https://user-images.githubusercontent.com/1048855/38857676-32533146-426d-11e8-8572-05954f418969.png">

### Reproducible Demo

The Example folder in the repo

**Comment by lazaronixon** [comment]
On 1.5.0 i changed first visit method to startSingleScreenApp.. update your example project and check if problem still exista

**Comment by nconroy** [comment]
Changing all instances of visit to startSingleScreenApp made no difference.

**Comment by nconroy** [comment]
Actually changing startTabBasedApp to startSingleScreenApp has fixed it. Thanks for your help

**Comment by lazaronixon** [comment]
Thank you... my bad.... https://github.com/lazaronixon/react-native-turbolinks/commit/7dc2dd7923f600f2751e452dad0a8e5729693a0d
