### ISSUE TITLE
Dynamic android styles

### ISSUE THREAD

**Issue by nconroy** [lazaronixon/react-native-turbolinks#16]
One of the requirements for our project is to be able to style the navigation via a remote api.
This works great for iOS as we can set the colours in navBarStlye. 
On Android we cant do this because colours are set from styles.xml. 
Is there any workaround for being able to style the android navigation dynamically?

**Comment by lazaronixon** [comment]
Currently no... I will put it on my list.

**Comment by lazaronixon** [comment]
Fixed https://github.com/lazaronixon/react-native-turbolinks/releases/tag/v1.6.4

**Comment by nconroy** [comment]
Could you give me an example of how this works, it is not working for me.

**Comment by nconroy** [comment]
I worked it out thanks 
menuIcon: await Icon.getImageSource('times', 20, 'white')

**Comment by nconroy** [comment]
How would I change the back button color?

**Comment by lazaronixon** [comment]
Try use navBarStyle: tintColor...

**Comment by nconroy** [comment]
That works for iOS but on android the back button is still black

**Comment by nconroy** [comment]
Here is the code that works on iOS

navBarStyle:
                    {
                        titleTextColor: this.config.toolbarColor,
                        subtitleTextColor: this.config.toolbarColor,
                        barTintColor: this.config.toolbarBackgroundColor,
                        tintColor: this.config.toolbarColor,
                        navBarTintColor: this.config.toolbarColor,
                        menuIcon: await Icon.getImageSource('ellipsis-v', 20, this.config.toolbarColor)
                    }

**Comment by nconroy** [comment]
@ramyalzayat no we are just using the styles.xml file

**Comment by huangc10** [comment]
@nconroy I tried implementing your solution in `android/app/src/main/res/values/styles.xml` but the back button remains black. Has something changed since July (this library or Android dev env)? Or perhaps is there some way to verify that the Android project is pointing to the styles.xml file?

I'm an iOS developer so quite new to Android dev. Thanks ahead for the help!

**Comment by lazaronixon** [comment]
@huangc10 I tested, and it is working.. You need copy all.
`<style name="AppTheme" parent="Theme.AppCompat.NoActionBar">`

**Comment by huangc10** [comment]
@lazaronixon I just figured it out it too and it was the AppTheme part (remove `light`). Cheers!

**Comment by lazaronixon** [comment]
I found a better solution... https://github.com/lazaronixon/react-native-turbolinks/blob/master/Example/android/app/src/main/res/values/styles.xml
