### ISSUE TITLE
Custom loading view not showing on iOS reloadSession()

### ISSUE THREAD

**Issue by nconroy** [lazaronixon/react-native-turbolinks#17]
The loading view works great everywhere except on iOS when calling reloadSession() where it just shows a blank screen. 
Without using the loadingView the spinner is shown correctly

**Comment by lazaronixon** [comment]
Fixed https://github.com/lazaronixon/react-native-turbolinks/releases/tag/v1.6.3

**Comment by nconroy** [comment]
Doesn't seem to be updated on npm yet

**Comment by lazaronixon** [comment]
My bad.. fixed
