### ISSUE TITLE
After page refresh in app that breaks event listeners 

### ISSUE THREAD

**Issue by dokuzbir** [lazaronixon/react-native-turbolinks#20]
In normal browser with full refresh, everything works as expected. But in app when i refresh page that breaks event listeners. My  event listeners are under turbolinks:load listener. what is difference beetwen browser refreshes and app page refreshes? 

Edit: for more details that affect only modals, sidenavbar other event listeners works as usual. I use materialize css modals and sidenavbar

**Comment by lazaronixon** [comment]
It seems problem with turbolinks. Try open a issue on Turbolinks Android or Turbolinks IOS
