### ISSUE TITLE
How to keep the tabs while navigating

### ISSUE THREAD

**Issue by scottharvey** [lazaronixon/react-native-turbolinks#24]
![screen](https://user-images.githubusercontent.com/78157/42731187-24d906de-8832-11e8-8daa-57d4c897189b.gif)

After I cilck a link on a page the tab navigation disappears. How to I make the tab navigation permanent?

**Comment by scottharvey** [comment]
What about making the tab bar permanently visible so it doesn't disappear like you see in the gif? Is that possible?

**Comment by hewrin** [comment]
@scottharvey Did you figure out a work around?

**Comment by lazaronixon** [comment]
This is default behavior on android... Check basecamp App
