### ISSUE TITLE
[Android] navIcon clickable?

### ISSUE THREAD

**Issue by ramyalzayat** [lazaronixon/react-native-turbolinks#25]
Hey @lazaronixon, 

I'm trying to find a solution for my app to add search icon in the navigation,
it works on IOS with leftButtonIcon and 
Turbolinks.addEventListener("turbolinksLeftButtonPress",this.handleLeftButtonPress);

So my solution to use navIcon on android and implement 'handleNavIconPress' in java

I followed handleTitlePress code and I did the same but I have one issue to identify navIcon on click,
so it works but the whole title area and navIcon clickable,

What should i do in this case?

Here is the code:

`protected void handleNavIconPress(final String component, final String url, final String path) {
        toolBar.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                WritableMap params = Arguments.createMap();
                params.putString("component", component);
                params.putString("url", url);
                params.putString("path", path);
                getEventEmitter().emit(TURBOLINKS_NAVICON_PRESS, params);
            }
        });
    }`

Thank you!

**Comment by lazaronixon** [comment]
You can use event turbolinksTitlePress

**Comment by ramyalzayat** [comment]
But i don't want the title to be clickable! , I want the NavIcon :)

**Comment by ramyalzayat** [comment]
in my case the whole area clickable now

`protected void handleNavIconPress(final String component, final String url, final String path) { toolBar.setOnClickListener(new View.OnClickListener() { public void onClick(View v) { WritableMap params = Arguments.createMap(); params.putString("component", component); params.putString("url", url); params.putString("path", path); getEventEmitter().emit(TURBOLINKS_NAVICON_PRESS, params); } }); }

`

**Comment by lazaronixon** [comment]
Ok I wil implement it when have a time

**Comment by ramyalzayat** [comment]
Could you please try to implement 
leftButtonIcon: A left button icon.

for android, it will be really useful. Thanks again looking forward.

**Comment by lazaronixon** [comment]
Android not provide a api to navIcon clicable, leftButtonIcon is not disponible too, you can use multiple actions with option button = true, It will create multiple right buttons
