### ISSUE TITLE
Turbolinks modal closes when using file upload element

### ISSUE THREAD

**Issue by nconroy** [lazaronixon/react-native-turbolinks#27]
When launching a component with a visit the modal is dismissed when trying to upload a file using a form file element.

`        Turbolinks.visit({
                component: 'ModuleView',
                modal: false});
`
Works well on Android but the component is dismissed when camera or photo gallery is loaded.

**Comment by nconroy** [comment]
Looks like it might be this bug: https://stackoverflow.com/questions/37380333/modal-view-closes-when-selecting-an-image-in-wkwebview-ios

**Comment by lazaronixon** [comment]
thank you... I will check it as possible

**Comment by nconroy** [comment]
By the way, the reason it has to be in a component is that for uploads to work on Android we have to use this https://github.com/andreipfeiffer/react-native-webview-android-file-upload

**Comment by nconroy** [comment]
Are you able to add this event overide:
`override func dismiss(animated flag: Bool, completion: (() -> Void)? = nil){
    if(self.presentedViewController != nil) 
    {
        super.dismiss(animated: flag, completion: completion)
    }
}`
This will fix the issue with file uploads on iOS turbolink modals
