### ISSUE TITLE
Use with other navigation components?

### ISSUE THREAD

**Issue by benreyn** [lazaronixon/react-native-turbolinks#3]
Is it possible to use this library with other react navigation libraries? My use case is building an app with a native tabbed navigation bar at the bottom of the screen, something like this.. 

https://snack.expo.io/@react-navigation/basic-tabs

Only each tab would be a Turbolinks view. In this example, one to `/home` and the other to `/settings`.

I've tried dropping in a few different navigation components but nothing seems to play nicely with `react-native-turbolinks` yet.

**Comment by fcatuhe** [comment]
Hi, I was investigating the same use case, and my conclusion for now is:
- we don't need all the navigation logic of navigation libraries like react-navigation or react-native-navigation,
- we only need the visual components, that we can get through UI libraries, like NativeBase Footer or Tabs components. Then we map the buttons to Turbolinks visits.

From my understading, the only native navigation element we get with Turbolinks is the top navbar, with customizable titles, back buttons and buttons, plus a menu.
The point I still don't get is how to use the menu actions to navigate.

@lazaronixon do I get it right?

**Comment by lazaronixon** [comment]
@fcatuhe I write a wiki to show how to use action menu to navigate.
https://github.com/lazaronixon/react-native-turbolinks/wiki/Simple-Menu-Actions

**Comment by benreyn** [comment]
Interesting... from what your are saying @lazaronixon, It seems like the design goal for the react-native implementation of turbolinks is a little different from the original implementation (or maybe the same but not as robust yet?)

I was expecting to be able to mix a turbolinks view with other react-native components similar to how the team at basecamp does. See [here](https://m.signalvnoise.com/basecamp-3-for-ios-hybrid-architecture-afc071589c25). I see in the example app that turbolinks is capable of "visiting" a react-native component similar to how it can visit a page. Is it a design goal to be able to mix other react-native components with the turbolinks view in this way? or is the idea to continue to build things on to the react-native-turbolinks api like you described above?

**Comment by benreyn** [comment]
Im also pretty curious what is happening when I _do_ render other components in the same component that I call `Turbolinks.visit` in `componentDidMount`. Is the Turbolinks view just taking over what the component is rendering? Or is something else happening that I could potentially work around?

**Comment by lazaronixon** [comment]
@benreyn You can visit a URL or a Component. Inside that component you can use any react-native element. Not is possible use navigator components so react-native-turbolinks wrap a turbolinks-view or react-native-component and provide NavBar, Menu, Tabs, Title, Subtitle etc... No components is rendered where first visit is called, but APIs like [actionsheetios](https://facebook.github.io/react-native/docs/actionsheetios.html) still works through all views.

**Comment by lazaronixon** [comment]
What exactly happens is that React-Native use a single IOSView/AndroidActivity to render components even navigators and turbolinks need native views. On IOS first view is replaced and in Android it is hidden.

**Comment by benreyn** [comment]
I see. So then in either case, the implementation may be different, but the turbolinks wrapper either contains a visit to a url OR a component, But if `Turbolinks.visit` is called with a url then anything that was rendered before that (like a navigation component) Then on ios the rendered component is replaced, and android it is hidden. Is that all correct?

**Comment by lazaronixon** [comment]
Exactly...

**Comment by benreyn** [comment]
Thanks for the clarification @lazaronixon. Ill close this issue, as youve answered my question 😄
