### ISSUE TITLE
Native authentication

### ISSUE THREAD

**Issue by scottharvey** [lazaronixon/react-native-turbolinks#30]
Is possible to do native authentication with this library the same way Turbolinks IOS describes it in their documentation?

https://github.com/turbolinks/turbolinks-ios/blob/master/Docs/Authentication.md#basecamp-3

> We handle that response by making a special request in a hidden WKWebView to an endpoint on our server using our OAuth token which sets the appropriate cookies for the web view.

Is that possible?

**Comment by lazaronixon** [comment]
Eu não enfrentei esse problema ainda. Minhas autenticações tem sido somente inside turbolinks webview. Mas eu acho que é mais facil com react-native-turbolinks, o que você tem que fazer é logar usando fetch API e dar um reloadSession para inserir os cookies no turbolinks webview.

**Comment by lazaronixon** [comment]
I have not faced this problem yet. My authentications have only been inside turbolinks webview. But I think it's easier with react-native-turbolinks, what you have to do is log in using fetch API and give a reloadSession to insert the cookies in the turbolinks webview.

**Comment by scottharvey** [comment]
ok thanks, I will try it out and if I get it working I'll create a Wiki page for it. Thanks 😄
