### ISSUE TITLE
popToRoot() without animation? && reloadVisitable()

### ISSUE THREAD

**Issue by ramyalzayat** [lazaronixon/react-native-turbolinks#32]
It would be great to be able to use Turbolinks.popToRoot(animated: false),
In my case, I use popToRoot to go to the root page then visit(/logout) and I have kind of blinkering because of the animated: true.

In the iOS app, if I use Turbolinks.reloadVisitable(); the app will crash any idea how to solve this?

Thanks

**Comment by lazaronixon** [comment]
I use something like.
```
Turbolinks.popToRoot
setTimeout(() => { Turbolinks.reloadSession() }, 1000)
```
I will check if is possible add a animated:false

**Comment by lazaronixon** [comment]
https://github.com/lazaronixon/react-native-turbolinks/releases/tag/v1.6.11
