### ISSUE TITLE
Still have issue with file uploads on IOS

### ISSUE THREAD

**Issue by nconroy** [lazaronixon/react-native-turbolinks#34]
#27 was closed by mistake
We need to check that the camera window isn't open before closing with this event:

override func dismiss(animated flag: Bool, completion: (() -> Void)? = nil){ if(self.presentedViewController != nil) { super.dismiss(animated: flag, completion: completion) } }
This will fix the issue with file uploads on iOS turbolink modals

**Comment by lazaronixon** [comment]
Since turbolinks-ios and turbolinks-android not support file upload I dont want provide a workarround...File uploads should be native for while
