### ISSUE TITLE
Turbolinks Android Deprecated

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [lazaronixon/react-native-turbolinks#37]
Thanks a lot for the amazing project

I am just starting to learn ReactNative.
I just noticed this DEPRECATION warning and I wanted to have your ideas

https://github.com/turbolinks/turbolinks-android/wiki/Turbolinks-Android-Adapter-1.x-Deprecation

thanks a lot
Fabrizio

**Comment by lazaronixon** [comment]
Thank you, I had not seen it yet.. I hope it get better.

**Comment by fabriziobertoglio1987** [comment]
@lazaronixon thanks a lot. I hope it too! I am currently learning react native, but once I have more experience I will further investigate ... 
Thanks a lot ! 
Fabrizio

**Comment by fabriziobertoglio1987** [comment]
@lazaronixon  [would you consider working on an upgrade to `turbolinks-android 2.0`](https://github.com/turbolinks/turbolinks-android) when comes out ? I am contacting Dan Kim on twitter for an update.

>Also, we are very early in the prototype stage for Turbolinks Android 2.0. We still don’t know the exact shape or even a rough timeline of when it might be available, but we plan to have something available in 2019.

>Thank you for supporting Turbolinks Android 1.0, and we’re excited to share 2.0 when the time comes.

I am new to react-native, I almost finished my first project and could be a good idea getting some opensource contributions sooner or later to get some more popularity.. 

I still wonder why your project got only 100 stars, being able to use the Turbolinks-Android/IOS webview could save me lots of time while still being able to build native application taking advantages of the many device apis...

Maybe react-native is very new and there are few developer who fluently know react-native and rails?

I may give the project a test trial on my next app which has some very good responsive pages!

Thanks a lot for the amazing project
Fabrizio

**Comment by lazaronixon** [comment]
You can get some tips from my new project [TheConstruct](https://github.com/lazaronixon/the_construct) https://www.youtube.com/watch?v=_p0S0Ll7o78

**Comment by fabriziobertoglio1987** [comment]
@lazaronixon Awesome - I did check TheConstruct and I am impressed with your opensource projects. 
`lazaronixon/react-native-turbolinks` has 100 stars, but `turbolinks/turbolinks-android` has only 359 stars, so relatively to `basecamp` your project has many stars.

1. `turbolinks-android` was deprecated, but it has only 10 issues, seems to me that the below issue has not flooded the repository with bugs. 

>Following a breaking change in Chrome 64, this Turbolinks 1.x adapter for Android hit an architectural dead end. Existing projects built with this version of the adapter will continue to work, although there may be some slow memory leaks and other minor issues.

2. Seems that the problem is Google not supporting this approach

>The old Turbolinks adapter can do the job for existing applications that were built on it, but it's hard for us to recommend that new applications be started on an older architectural model when Google is actively recommending a new, single-activity approach.

Their answer

>But although MutableContextWrapper is a valid public Android API, the Chromium team consistently reiterated that relying on that wasn’t a good idea and that swapping contexts would always be a risky proposition. In the end, the Chromium team was unwilling to make any changes to their implementation and advised us to change our approach or live with this issue.

so I believe we should expect a new version in 2019

and they released a temporary patch to fix the  [Chrome 64 accessibility bug/crash](https://github.com/turbolinks/turbolinks-android/releases/tag/1.0.8)

I will use this repo, I have 5 Ruby on Rails Web Apps with responsive layouts. I can quickly port them to React-Native with this awesome project and add native features.

I hope that I don't end up in too many issues, but both repos have few issues open so I'll be optimistic

Thanks

**Comment by fabriziobertoglio1987** [comment]
@lazaronixon I think the issues will come out once new chrome browser is adopeted as the api used from turbolinks android is not anymore available in chrome...

Is that right? because I am interested in this project

**Comment by lazaronixon** [comment]
Honestly, I haven't seen any issues with this version of turbolinks android yet.

**Comment by nconroy** [comment]
Android works well as far as I have seen

**Comment by kylesziv** [comment]
Looks like Turbolinks was replaced with Turbo

https://github.com/hotwired/turbo-android

**Comment by lazaronixon** [comment]
I cant wait to make it happen 😋😋😋

**Comment by lazaronixon** [comment]
#80
