### ISSUE TITLE
Can no longer get evaluated JS

### ISSUE THREAD

**Issue by nconroy** [lazaronixon/react-native-turbolinks#38]
I am trying to upgrade my app to the latest RNTurbolinks but it seems to be missing a function my app relies on: 
` const script = 'document.documentElement.outerHTML';`
` Turbolinks.evaluateJavaScript(script).then((source) => {`
 `           const $ = cheerio.load(source);`
`            //Extract stuff from the source using cheerio       `
`       });`

I can see there is now an 'injectJavaScript' function but that doesn't seem to return a promise or anything else. Is there any chance of adding this back in? 
Or how should I be getting the HTML of the page to be able to parse it?

**Comment by lazaronixon** [comment]
Cheerio is not supported anymore... You should write your js on webpage and use `injectJavaScript` and use `turbolinksMessage` event if you want any return value.
