### ISSUE TITLE
[Android] TabBar title and actions are not taken into account

### ISSUE THREAD

**Issue by fcatuhe** [lazaronixon/react-native-turbolinks#4]
Hi @lazaronixon, thanks again for the great work on TabBar!

I have this issue only on Android with the following setting in `componentDidMount()`:
```javascript
Turbolinks.setTabBar({
  routes: [
    {
      tabTitle: 'Home',
      title: 'RNT Showcase',
      url: env.BASE_URL,
      actions: [{ id: 404, title: '404 error' }]
    },
    {
      tabTitle: 'Posts',
      title: 'View all posts',
      url: `${env.BASE_URL}/posts`,
      actions: [{ id: 11, title: 'New post' }]
    }
  ]
});
```
The title and actions on all Tabs are the ones of the first route only, they do not change when navigating to other tabs.

It works as expected on iOS.

I brought up a repo for my experiments ;-) available here: [RNT Showcase](https://github.com/fcatuhe/rnt-showcase)

**Comment by lazaronixon** [comment]
Unfortunately this is the default behavior on android. On android we have a component called PagerView where it is possible slide between views so I used it to slide between TurbolinksViews and NativeViews but with only one Toolbar. By default react-native-turbolinks will use route from selectedIndex to mount this single toolbar. If possible see baseCamp App for android. You will see the same behavior.

**Comment by lazaronixon** [comment]
What could be done is I implement a eventListener like `turbolinksTabChanged` with selectedIndex as return. So you could use on JavaScript side renderActions or renderTitle methods... But i think it would be a lot of code to you implement only for android for to do a not soo important feature. If I have more requests i can do that.

**Comment by fcatuhe** [comment]
OK thanks for the explanation, for the moment I will explore the possibilities with this configuration!
