### ISSUE TITLE
Show In app notification

### ISSUE THREAD

**Issue by acapilleri** [lazaronixon/react-native-turbolinks#41]
Hello, 
we are trying to show a in app push-notification.  There is some way to display a component like the this notification? I tried to use visit modal but it takes the entire screen by default, and it is not possibile to change the size

**Comment by lazaronixon** [comment]
No.. I think it is not possible in turbolinks views... You can try my other lib https://github.com/lazaronixon/react-native-form-sheet

**Comment by acapilleri** [comment]
Actually we have this feature on our turbolinnks ios app
