### ISSUE TITLE
Feature Request: Position Network Activity Indicator

### ISSUE THREAD

**Issue by leigh-mackay** [lazaronixon/react-native-turbolinks#43]
Being able to position the activity indicator would complement automaticallyAdjustContentInsets and contentInset.

The layout I'm tinkering with has a sticky footer with hidden navbar.

Turbolinks.startSingleScreenApp({ url: baseUrl, navBarHidden: true }, {automaticallyAdjustContentInsets: false, contentInset: { top: 0, left: 0, bottom: -17, right: 0 }})

The progress indicator is hugging the top of the screen, would be nice to be able to adjust it.

![IMG-1748](https://user-images.githubusercontent.com/52640620/61536026-d64ee880-aa72-11e9-8b24-afcab1ce40af.JPG)

Is there a workaround? can I just edit the RTTurbolinksManager.swift?

Great project, thank you.

**Comment by lazaronixon** [comment]
You should use positive top value instead.
