### ISSUE TITLE
React Native 0.60

### ISSUE THREAD

**Issue by acapilleri** [lazaronixon/react-native-turbolinks#46]
Did you plan a pod version for the new React Native 0.60 ?

**Comment by lazaronixon** [comment]
Yep.. I am very excited about react hooks and the possibility to use cocoapods to download turbolinks ios lib. I am waiting for new version of turbolinks android that is almost about to release, but the main problem is that I am working a lot, I recently get off work and I am finding new ways to make money, so it can be good for react native turboli ks... or not..

**Comment by lazaronixon** [comment]
Fixed
