### ISSUE TITLE
Update navBarStyle to include borderBottomWidth & borderBottomColor

### ISSUE THREAD

**Issue by snellingio** [lazaronixon/react-native-turbolinks#47]
Please allow for the `borderBottomWidth` & the `borderBottomColor` to be set in the `navBarStyle` property, including `renderNavBarStyle(navBarStyle)`

**Comment by lazaronixon** [comment]
This is not natively supported... There are several workarounds, but none of them conquered me.

**Comment by snellingio** [comment]
Sounds good 👍

**Comment by lazaronixon** [comment]
`hidesShadow`: Indicates whether to hide the navigation 1px hairline shadow. (Default false) (iOS Only)

added hidesShadow
