### ISSUE TITLE
Add ability to get the current route or current path of Turbolinks instance

### ISSUE THREAD

**Issue by snellingio** [lazaronixon/react-native-turbolinks#48]
Looking for a method to get the current path `/current/path` or url `https://app.com/current/path` of current Turbolinks instance.

This would be useful in determining what to do in a lot of cases, including, when a modal is open in front of the Turbolinks view.

`Turbolinks.getCurrentPath()` or `Turbolinks.getCurrentUrl()`

**Comment by lazaronixon** [comment]
You can use turbolinksVisit event to get current path and put it on a variable..

**Comment by lazaronixon** [comment]
Return `url, path, component, actionId` on turbolinksActionPress
