### ISSUE TITLE
Ability to render one action as a button

### ISSUE THREAD

**Issue by snellingio** [lazaronixon/react-native-turbolinks#49]
See the "edit" button.

![IMG_0516](https://user-images.githubusercontent.com/9887585/70062922-982f0d00-15ac-11ea-9f18-420da4dd3b0c.jpeg)

I already do something similar to this with the `react-native-navbar` in the modal example.

This is less of a priority to me personally.

**Comment by lazaronixon** [comment]
You can use rightButtonIcon on ios

**Comment by lazaronixon** [comment]
I can create rightButtonText property, works to you?
leftButtonIcon/leftButtonText
rightButtonIcon/rightButtonText

**Comment by lazaronixon** [comment]
fixed
