### ISSUE TITLE
[Android] Swiping between tabs does not update active tab

### ISSUE THREAD

**Issue by fcatuhe** [lazaronixon/react-native-turbolinks#5]
As the title explains, in Android we can swipe between tabs, but only the view swipes, not the active tab in the tab bar.

Tapping on a tab works (updates active tab and displays corresponding view).

Edit: link to [test application](https://install.appcenter.ms/users/fcatuhe/apps/rnt-showcase/distribution_groups/github%20testers)

**Comment by lazaronixon** [comment]
My intention is disable it ...

**Comment by lazaronixon** [comment]
7392f8b7aaf0ee122412b47e2b221e0e39a1820f Should fix it. I couldn't test it on emulator.

**Comment by fcatuhe** [comment]
OK tested, swipe is now disabled 👍
