### ISSUE TITLE
Brainstorming how to make a tablet interface

### ISSUE THREAD

**Issue by snellingio** [lazaronixon/react-native-turbolinks#50]
Basecamp uses a two column layout. What they are doing is they are showing a native "view" on the left, and the Turbolinks holder on the right.

![IMG_0204](https://user-images.githubusercontent.com/9887585/70063344-36bb6e00-15ad-11ea-9fba-881bab496f40.jpeg)

If we could figure out a way to have a secondary view on the screen, it could work similar to the tab example in the wiki with a webview instance.

Of course, the correct answer might be "do a sidebar in your HTML" which is how Youtube works. 

![IMG_0205](https://user-images.githubusercontent.com/9887585/70063350-38853180-15ad-11ea-848c-c8f26d0cabba.PNG)

**Comment by lazaronixon** [comment]
Could you post a gif with more details of how basecamp works on ipad please? I dont have ipad here

**Comment by snellingio** [comment]
They use native screens on the left, similar to the App.

![RPReplay_Final1575388078 2](https://user-images.githubusercontent.com/9887585/70066660-ac760880-15b2-11ea-80c2-c969b273c1d2.gif)

On the right, they just have a big webview. This does everything the current Turbolinks view does.

![RPReplay_Final1575388078](https://user-images.githubusercontent.com/9887585/70066716-c0ba0580-15b2-11ea-8669-f8f34d08802e.gif)

**Comment by lazaronixon** [comment]
I am investigating it, and as pointed here https://m.signalvnoise.com/basecamp-3-for-ios-hybrid-architecture basecamp seems use UISplitViewController, I will think some API for that.

**Comment by lazaronixon** [comment]
now you can use `Turbolinks.startSplitScreenApp('NumbersView', {url: baseUrl})` where the first argument is a nativeView and the second a route.

**Comment by lazaronixon** [comment]
I added a collapse button to splitScreen on last version.

**Comment by lazaronixon** [comment]
I found a way to set secondary view as default on mobile
