### ISSUE TITLE
Webview scrolls when content does not exceed viewport

### ISSUE THREAD

**Issue by sinor38058** [lazaronixon/react-native-turbolinks#52]
Hi, so I've noticed on all my screens the that the webview is scrollable. This caused an issue when using a floating action button with [materializecss.css](https://materializecss.com/floating-action-button.html) as it's hidden until you scroll to it.

Is there something special I need to do to prevent the scrolling or only scroll when content is long enough?

In the first screenshot, I'm able to scroll down further

In the second screenshot, the starting position which is unscrolled shows that it's already scrolled down. I believe this is the issue that I have as the floating action button positions itself with a `fixed` position bottom right of screen-based e.g

```
.fixed-action-btn {
    position: fixed;
    right: 23px;
    bottom: 23px;
    padding-top: 15px;
    margin-bottom: 0;
    z-index: 997;
}
```

![Screen Shot 2019-12-21 at 9 07 37 pm](https://user-images.githubusercontent.com/59112654/71306560-f32e8400-2435-11ea-93d2-e593cd88cb2d.png)
![Screen Shot 2019-12-22 at 9 13 35 am](https://user-images.githubusercontent.com/59112654/71314395-95cd1e00-249b-11ea-8eae-1d9d85e255a5.png)

**Comment by sinor38058** [comment]
I added a floating action button from the materializecss lib to the example app. Heres a better demonstration of the issue:

I added this to the layout.erb `<head>` section 

```
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
```

and this to index.erb

```
<div class="fixed-action-btn">
  <a class="btn-floating btn-large red">
    <i class="large material-icons">mode_edit</i>
  </a>
  <ul>
    <li><a class="btn-floating red"><i class="material-icons">insert_chart</i></a></li>
    <li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
    <li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
    <li><a class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>
  </ul>
</div>

```

![screencast 2019-12-22 09-26-14](https://user-images.githubusercontent.com/59112654/71314484-5dc6da80-249d-11ea-85bd-a4e3e6e9558f.gif)

**Comment by lazaronixon** [comment]
It is not supported by turbolink-ios, since scroll provides refresh for pages too.. If you want this kind of button it should be implemented with native view maybe using https://github.com/santomegonzalo/react-native-floating-action

**Comment by sinor38058** [comment]
thanks @lazaronixon, I'll look into that.
