### ISSUE TITLE
turbolinksRightButtonPress event doesn't work

### ISSUE THREAD

**Issue by sinor38058** [lazaronixon/react-native-turbolinks#53]
I've got the event setup like this in the example app:

App.js
```
  componentDidMount() {
    Turbolinks.addEventListener(
      'turbolinksRightButtonPress',
      this.rightButtonPress,
    );

    Turbolinks.startSingleScreenApp(
      {url: baseUrl, rightButtonText: 'righty'},
      {messageHandler: 'turbolinksDemo'},
    );
  }

  rightButtonPress = () => {
    alert('why you no work??');
  };

=
```

When pressing the right nav bar link, nothing happens. However if I update the event to this:

```
    Turbolinks.addEventListener(
      'turbolinksLeftButtonPress',
      this.rightButtonPress,
    );
```

It works fine

![screencast 2019-12-24 19-29-49](https://user-images.githubusercontent.com/59112654/71403437-de473000-2683-11ea-9acd-0ea8acea657a.gif)

**Comment by lazaronixon** [comment]
fixed https://github.com/lazaronixon/react-native-turbolinks/releases/tag/v2.2.4

**Comment by sinor38058** [comment]
thanks, @lazaronixon works now
