### ISSUE TITLE
devise wiki might be incorrect

### ISSUE THREAD

**Issue by sinor38058** [lazaronixon/react-native-turbolinks#54]
https://github.com/lazaronixon/react-native-turbolinks/wiki/Authentication-Devise

I think the wiki might be incorrect:

In the wiki the `handleAuthentication` method within `AuthenticationView.js` is used in the `WebView` `onLoadStart` callback.

When using it I noticed it was only being called when loading. But when successfully signing in, it would continue using the modal.

If I change

```
        <WebView ref={webview => { this.webview = webview }}
                 source={{uri: signInUrl}}
                 onLoadStart={this.handleAuthentication}/>
```

to

```
        <WebView ref={webview => { this.webview = webview }}
                 source={{uri: signInUrl}}
                 onLoad={this.handleAuthentication}/>
```

It will close the modal, otherwise, the method is never called again if using `onLoadStart`

**Comment by lazaronixon** [comment]
Did you tried disable turbolinks on login form ? ReactNative WebView cant intercept turbolinks links. you should use remote: false on form.

**Comment by lazaronixon** [comment]
The ideia is check after signin if webview is redirected to correct url and stop this unnecessary load. After that with cookies well set, you can dismiss modal and reloadSession on turbolinks

**Comment by sinor38058** [comment]
ah! that was the problem. Thanks again @lazaronixon. That may be a good thing to add to the wiki.
