### ISSUE TITLE
Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.0 compiler

### ISSUE THREAD

**Issue by leigh-mackay** [lazaronixon/react-native-turbolinks#55]
Got this error when trying out the demo.

xcode: 10.2 and swift 5.0

Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.0 compiler

![Screen Shot 2019-12-28 at 3 29 12 pm](https://user-images.githubusercontent.com/52640620/71539095-00dc9000-2987-11ea-88e7-7169c3a520c3.png)

so installed toolchain for 5.1.2 and that removed the above error but made a new error.

![Screen Shot 2019-12-28 at 3 26 53 pm](https://user-images.githubusercontent.com/52640620/71539111-692b7180-2987-11ea-893d-4ca0c522a3cd.png)

I'm not sure what is happening as this used to work.

**Comment by lazaronixon** [comment]
Update xcode to 10.3

**Comment by lazaronixon** [comment]
Update xcode to 11.3

**Comment by leigh-mackay** [comment]
Thank you, worked :D
