### ISSUE TITLE
How to access styles of actions menu

### ISSUE THREAD

**Issue by nconroy** [lazaronixon/react-native-turbolinks#56]
How can I change the styles of the action menu?
We need to prevent the menu using the text size from ios:
![Simulator Screen Shot - iPhone 11 Pro - 2020-01-10 at 13 44 15](https://user-images.githubusercontent.com/1048855/72121502-52d1dc80-33af-11ea-8200-ff04f74f1aff.png)

Also, some styling seems to add padding to the top?
![Simulator Screen Shot - iPhone X - 2020-01-10 at 13 45 23](https://user-images.githubusercontent.com/1048855/72121587-92002d80-33af-11ea-95a2-e5c4f21e729f.png)

**Comment by lazaronixon** [comment]
Good question.. I will check and return soon as possible...

**Comment by nconroy** [comment]
Alternatively, it would be good to know how to use a react-native-side-menu with turbolinks?

**Comment by lazaronixon** [comment]
Well.. what I can do is set fixed font size... You can use this kind of component only on native views.. I dont recommend it..

**Comment by nconroy** [comment]
You don't recommend using the Actions menu?

**Comment by lazaronixon** [comment]
I don't recommend react-native-side-menu. In wish circumstance did you see this padding on top?

**Comment by lazaronixon** [comment]
fixed https://github.com/lazaronixon/react-native-turbolinks/releases/tag/v2.2.5

**Comment by nconroy** [comment]
Thanks!
