### ISSUE TITLE
Back swipe gesture

### ISSUE THREAD

**Issue by nconroy** [lazaronixon/react-native-turbolinks#57]
How hard is it to enable the back (left-edge) gesture as you can in the UINavigation controller?
This would really add to the feel of being native and some of my users keep pointing out that they cant do this.

**Comment by lazaronixon** [comment]
Slide(—>) should back to previous page... it is not working on example?

**Comment by lazaronixon** [comment]
![ScreenFlow](https://user-images.githubusercontent.com/2651240/72533687-54d6e800-3854-11ea-8923-e52b02f2dd1c.gif)

**Comment by lazaronixon** [comment]
![ScreenFlow](https://user-images.githubusercontent.com/2651240/72534134-1261db00-3855-11ea-9545-00265cff69a0.gif)

**Comment by lazaronixon** [comment]
![ScreenFlow](https://user-images.githubusercontent.com/2651240/72534358-6f5d9100-3855-11ea-9038-1c84b36b30ab.gif)
