### ISSUE TITLE
loadingView appOption slows down app

### ISSUE THREAD

**Issue by leigh-mackay** [lazaronixon/react-native-turbolinks#60]
Added a content loader and the app is much slower when clicking. There seems to be a big delay from when I click to when the rails console logs anything.

Followed the information on the Wiki and I'm using that exact example.

Is there any way to make it faster?

**Comment by leigh-mackay** [comment]
It starts out fast and then after clicking around a few times the time from when I click a link to the time I see the rails console log something is over a second.

**Comment by ghost** [comment]
Does not happen anymore :)
