### ISSUE TITLE
Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.2 compiler: 

### ISSUE THREAD

**Issue by nconroy** [lazaronixon/react-native-turbolinks#61]
I had to reinstall xcode and upgraded to 11.4 
I now get this error:
Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.2 compiler: 
***/node_modules/react-native-turbolinks/ios/Turbolinks.framework/Modules/Turbolinks.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
I have reinstalled turbolinks and cleaned the project

Any ideas?

**Comment by lazaronixon** [comment]
I will check....

**Comment by lazaronixon** [comment]
Fixed https://github.com/lazaronixon/react-native-turbolinks/releases/tag/v2.2.6
