### ISSUE TITLE
Error running `bundle install`

### ISSUE THREAD

**Issue by xerervw** [lazaronixon/react-native-turbolinks#62]
Hi, I'm new to react native and turbolinks. 
While trying to run the demo-server. I keep getting this error: 

Starting the demo server (press ^C to exit)...
Installing Bundler...
Installing dependencies...
Error running `bundle install`

Could someone help me with this? I have no idea what is causing this..

Thanks

**Comment by lazaronixon** [comment]
try execute `bundle install` inside /server path

**Comment by xerervw** [comment]
Thanks for your swift reply. 
I think bundle installed successfully. When I try to run: bundle exec rackup --host 0.0.0.0

I get the following result:

/Users/maarten/.rvm/gems/ruby-2.7.1/gems/sinatra-2.0.0/lib/sinatra/base.rb:1638: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/maarten/.rvm/gems/ruby-2.7.1/gems/mustermann-1.0.1/lib/mustermann.rb:62: warning: The called method `new' is defined here
/Users/maarten/.rvm/gems/ruby-2.7.1/gems/mustermann-1.0.1/lib/mustermann/pattern.rb:59: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/maarten/.rvm/gems/ruby-2.7.1/gems/mustermann-1.0.1/lib/mustermann/regular.rb:22: warning: The called method `initialize' is defined here
/Users/maarten/.rvm/gems/ruby-2.7.1/gems/sinatra-2.0.0/lib/sinatra/base.rb:1601: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/maarten/.rvm/gems/ruby-2.7.1/gems/sinatra-2.0.0/lib/sinatra/base.rb:1618: warning: The called method `compile!' is defined here
/Users/maarten/.rvm/gems/ruby-2.7.1/gems/mustermann-1.0.1/lib/mustermann/pattern.rb:59: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/maarten/.rvm/gems/ruby-2.7.1/gems/mustermann-1.0.1/lib/mustermann/regexp_based.rb:17: warning: The called method `initialize' is defined here
/Users/maarten/.rvm/gems/ruby-2.7.1/gems/mustermann-1.0.1/lib/mustermann/ast/compiler.rb:43: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/maarten/.rvm/gems/ruby-2.7.1/gems/mustermann-1.0.1/lib/mustermann/ast/compiler.rb:49: warning: The called method `pattern' is defined here
[2020-04-19 09:41:08] INFO  WEBrick 1.6.0
[2020-04-19 09:41:08] INFO  ruby 2.7.1 (2020-03-31) [x86_64-darwin19]
[2020-04-19 09:41:08] INFO  WEBrick::HTTPServer#start: pid=14480 port=9292

Shouldn't it return or do anyhting?

**Comment by lazaronixon** [comment]
well it seens only deprecated warning because you are using ruby 2.7.1 but now it seens runing on port 9292... try on browser http://localhost:9292

**Comment by xerervw** [comment]
Okay how do I do that..? Currently have it like this in app.json:

{
  "name": "Example",
  "displayName": "Example",
  "baseUrl": "http://localhost:9292"
}

Or do I have to change something else?

**Comment by xerervw** [comment]
Got it.. :) Didn't know what was happening.. Thanks for the help!

**Comment by lazaronixon** [comment]
> Okay how do I do that..? Currently have it like this in app.json:
> 
> 
> 
> {
> 
>   "name": "Example",
> 
>   "displayName": "Example",
> 
>   "baseUrl": "http://localhost:9292"
> 
> }
> 
> 
> 
> Or do I have to change something else?

Try use your local ip instead localhost

**Comment by lazaronixon** [comment]
fixed https://github.com/lazaronixon/react-native-turbolinks/commit/258c55cf2b2ab7986afe8d7f44c45edc632cc19e
