### ISSUE TITLE
Stuck at launch

### ISSUE THREAD

**Issue by xerervw** [lazaronixon/react-native-turbolinks#63]
Everything seems to be working fine until the app gets stuck when launching the first screen.
No idea what is causing this..

React native is logging this:
[Sun Apr 19 2020 18:28:22.485]  LOG      Running "StupoPlatform" with {"rootTag":1,"initialProps":{}}

Could someone help me with this?
Thanks

**Comment by xerervw** [comment]
I think something is going wrong with the combination of turbolinks and perhaps my web app. The standard screen when creating a react native app does load.

**Comment by lazaronixon** [comment]
Try use you local ip instead localhost

**Comment by xerervw** [comment]
Thanks for your swift reply.

tried this:
    Turbolinks.startSingleScreenApp({url: 'IPv4-adress'});

this returns:
Alert
This requested url has not been found on this server.

Also tried this:
    Turbolinks.startSingleScreenApp({url: 'IPv4-adress:3000'});

this returns:
Alert
The url can't be shown.

**Comment by lazaronixon** [comment]
You should use you local address like 192.168.0.xxx

**Comment by xerervw** [comment]
I did it like this:
    Turbolinks.startSingleScreenApp({url: 'IP'});
got the ip adress from here:

<img width="610" alt="Schermafbeelding 2020-04-19 om 21 06 26" src="https://user-images.githubusercontent.com/61314796/79697234-d5f1b100-8281-11ea-8a11-e2c956a885e3.png">

Am I doing something wrong?

**Comment by lazaronixon** [comment]
If you are using server example it should be 192.168.0.100:9292

**Comment by xerervw** [comment]
I keep getting this response: 

<img width="246" alt="Schermafbeelding 2020-04-19 om 23 08 51" src="https://user-images.githubusercontent.com/61314796/79700083-a8156800-8293-11ea-93f7-b4b01f252da9.png">

**Comment by lazaronixon** [comment]
it is opening on browser?

**Comment by xerervw** [comment]
No it isn't.. 
I tried npx react-native run-ios with http://localhost:9292
Returned: 'Can't connect to server'

also tried npx react-native start
but It doesn't work in browser..

**Comment by lazaronixon** [comment]
The problem seens to be on server... I updated server to run on ruby 2.7.1... clone and try to run ./demo-server
