### ISSUE TITLE
Tabbar troubles with Turbolinks

### ISSUE THREAD

**Issue by jankeesvw** [lazaronixon/react-native-turbolinks#64]
First of all, thanks for this great library. I'm trying to accomplish something but I can't get it to work. I would like to have a tab bar in combination this library. I tried the code in the Wiki and modified it a bit to work with React Navigation.
   
And this is how it looks, as you can see it doesn't behave like a Turbolinks app it looks like regular webviews in tabs. Does anyone have any pointers on how to fix this, or maybe a working example?

![ScreenFlow-min](https://user-images.githubusercontent.com/167882/81001379-eb510880-8e47-11ea-8c52-60b2b728c8fb.gif)

This is what I currently have:

**App.js**

```js
import React, {Component} from 'react';
import Turbolinks from 'react-native-turbolinks';

export default class App extends Component {
  componentDidMount() {
    Turbolinks.startSingleScreenApp({title: 'App', component: 'TabbedView'});
  }

  render() {
    return null;
  }
}
```

**TabbedView.js**

```js
import React, {Component} from 'react';
import {Text, ScrollView, SafeAreaView} from 'react-native';
import {WebView} from 'react-native-webview';
import Turbolinks from 'react-native-turbolinks';

import {NavigationContainer} from '@react-navigation/native';
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';

const baseUrl = 'http://localhost:9292/';
const anotherURL = 'http://localhost:9292/';

class Home extends Component {
  onLoadStart = event => {
    if (event.nativeEvent.url != baseUrl) {
      this.webview.stopLoading();
      Turbolinks.visit({url: event.nativeEvent.url});
    }
  };

  render() {
    return (
      <SafeAreaView style={{flex: 1}}>
        <WebView
          ref={webview => {
            this.webview = webview;
          }}
          source={{uri: baseUrl}}
          onLoadStart={this.onLoadStart}
        />
      </SafeAreaView>
    );
  }
}
class Aanmelden extends Component {
  onLoadStart = event => {
    if (event.nativeEvent.url != baseUrl) {
      this.webview.stopLoading();
      Turbolinks.visit({url: event.nativeEvent.url});
    }
  };

  render() {
    return (
      <SafeAreaView style={{flex: 1}}>
        <WebView
          ref={webview => {
            this.webview = webview;
          }}
          source={{uri: anotherURL}}
          onLoadStart={this.onLoadStart}
        />
      </SafeAreaView>
    );
  }
}

class Profile extends Component {
  render() {
    return (
      <ScrollView style={{flex: 1, backgroundColor: 'white', height: '100%'}}>
        <Text style={{flex: 1}}>
          Native view Native view Native view....
        </Text>
      </ScrollView>
    );
  }
}

const Tab = createBottomTabNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Tab.Navigator>
        <Tab.Screen name="Home" component={Home} />
        <Tab.Screen name="Profile" component={Profile} />
        <Tab.Screen name="Aanmelden" component={Aanmelden} />
      </Tab.Navigator>
    </NavigationContainer>
  );
}
```

**Comment by lazaronixon** [comment]
I don’t recommend use react-native-navigation with react-native-turbolinks... If you want use tabbar, for now you need use it on on first view as component using react-native-tabbar... It will prevent many complexity about handle multiple turbolinks visit on different webviews... you can check this behaviour on basecamp android... you will notice that basecamp IOS is mutlitask tabbar and android is visible only on first screen as native component

**Comment by jankeesvw** [comment]
> I don’t recommend use react-native-navigation with react-native-turbolinks... If you want use tabbar, for now you need use it on first view as component using react-native-tab-navigator ... It will prevent many complexity about handle multiple turbolinks visit on different webviews... you can check this behaviour on basecamp android... you will notice that basecamp IOS is mutlitask tabbar and android is visible only on first screen as native component

What would you suggestion be? Making the tab bar part of the HTML?

**Comment by lazaronixon** [comment]
No... I suggest exactly as wiki https://github.com/lazaronixon/react-native-turbolinks/wiki/Tab-Navigator, your first screen should be a native screen through `Turbolinks.startSingleScreenApp({title: "App", component: "TabbedView"})` and inside each tab you can put a component or a webview and intercept click on links and call `Turbolinks.visit({url: event.nativeEvent.url})`. The drawback is that tabbar will bi visible only on first screen of your app...

**Comment by lazaronixon** [comment]
Don't forget to put data-turbolinks="false" on pages showed on `<WebView>`... Otherwise `onLoadStart` event wont will be called...

**Comment by jankeesvw** [comment]
And there is not way to make an app like Basecamp has, with a tab bar on every page?

**Comment by jankeesvw** [comment]
The problem would be solved if you could wrap the react-native-webview in another React Native view.

**Comment by lazaronixon** [comment]
Check basecamp android, It is a problem for then too... I implemented it on the past but it brings some complexity to api since you will need to handle multiple visits on different tabs and tabs should be natively implemented, My first try with this lib was make turbolinks-webview available as a component but it is only a piece of that... At really turbolinks is more a navigation lib than a component.

**Comment by jankeesvw** [comment]
I'm not sure how I'm going to solve it, but it feels a bit weird if the tab bar is only visible on the root page. I'll let you know if I come up with something.

**Comment by jankeesvw** [comment]
@lazaronixon I first tried it with [react-native-tab-navigator](https://github.com/ptomasroos/react-native-tab-navigator) and got it working in the way you describe. Unfortunately this library has some depredations: 

https://github.com/ptomasroos/react-native-tab-navigator/issues/200
https://github.com/ptomasroos/react-native-tab-navigator/issues/198

<img width="474" alt="image" src="https://user-images.githubusercontent.com/167882/81103328-2d924c80-8f11-11ea-86d7-8a6dc3b83ff9.png">

Then I switched back to React Navigation and got it working when I disabled TurboLinks on one of the links:

![CleanShot 2020-05-05 at 20 42 43](https://user-images.githubusercontent.com/167882/81103479-616d7200-8f11-11ea-8af6-7c5f1ed24940.gif)

This is what you mean right, @lazaronixon?

**Comment by lazaronixon** [comment]
👍  very nice... I will correct my self.. I recommend use React Navigation  with moderation...

**Comment by lazaronixon** [comment]
better ever, maybe you only need this component of react-navigation ... https://github.com/react-navigation/react-navigation/tree/master/packages/bottom-tabs

**Comment by jankeesvw** [comment]
Exactly using bottom-tabs in that GIF. 👌 

Unfortunately this library is not usable for my app. I would need to keep the tab bar on every page so people can easily jump between sections. It would be solved if I could use the TurbolinksWebView as a regular react component.

**Comment by lazaronixon** [comment]
Maybe it bring back on future... I am planning some improvements with next version of turbolinks...

**Comment by jankeesvw** [comment]
Is there a way I can try how this works?

**Comment by lazaronixon** [comment]
Not now... Take a look on Basecamo Android.
![basecamp-android](https://user-images.githubusercontent.com/2651240/81114552-a0db9480-8ef8-11ea-835b-edb462e0e712.gif)

**Comment by jankeesvw** [comment]
> Not now... Take a look on Basecamp Android.

Yes you are right, Android is not keeping that tab bar. Unfortunately this is not common on iOS.

**Comment by mattwoberts** [comment]
@jankeesvw Hi - hope you don't mind me asking you - if you decided not to use this, what approach did you take?

I'm doing something similar for a hybrid app in similar style to basecamp - I want a tab accross the bottom, with a screen in each one, and webviews in each screen. 

Currently, I'm doing this without turbolinks. So each tab has a screen, each screen has a webview, and I handle interactions between the web app and my mobile app. But I'm concerned this is going to get tricky to maintain, and I'm also concerned that the number of screens I end up having - each with it's own webview, is going to put a high load on the memory footprint of the app.

Thanks.

Matt

**Comment by lazaronixon** [comment]
It is possible only on first screen... next screens should overlaps tabbar.
