### ISSUE TITLE
Append param key to every GET URL

### ISSUE THREAD

**Issue by wonderer007** [lazaronixon/react-native-turbolinks#66]
I want to append a parameter to every time we make the `GET` request we make. For example, appending `mobileapp=true`.

Is there any callback to do this?

**Comment by lazaronixon** [comment]
Is better use a special userAgent for your app and check it on server... React Native Turbolinks provide a option for that... Turbolinks.startSingleScreenApp({url: 'http://MYIP:9292'}, {userAgend: 'mobileapp'})
