### ISSUE TITLE
Invariant Violation: "TabbedView" has not been registered

### ISSUE THREAD

**Issue by wonderer007** [lazaronixon/react-native-turbolinks#69]
I am working with [Tab Navigator](https://github.com/lazaronixon/react-native-turbolinks/wiki/Tab-Navigator) docs. I just followed the docs but getting the following error

<img width="425" alt="Screen Shot 2020-06-21 at 1 38 47 PM" src="https://user-images.githubusercontent.com/2243326/85222695-c18f7900-b3d6-11ea-8771-408f29a9cb47.png">

Is it something related to react-native version I am using? I am using `react-native: 0.62.2`

Thanks!

**Comment by lazaronixon** [comment]
You need register the component on index.js... do the same as NumberView.
https://github.com/lazaronixon/react-native-turbolinks/blob/master/Example/index.js
