### ISSUE TITLE
setNavigationBarHidden crashes app

### ISSUE THREAD

**Issue by Bickson** [lazaronixon/react-native-turbolinks#8]
@lazaronixon Hi, I just started a new project and everything works fine until I add `Turbolinks.setNavigationBarHidden(true)`. then the app won't start at all.

```
componentDidMount() {
    Turbolinks.setNavigationBarHidden(true)
    Turbolinks.addEventListener('turbolinksVisit', this.handleVisit)
    Turbolinks.addEventListener('turbolinksError', this.handleError)
    Turbolinks.visit({url: url}, true)
  }
```

`Fatal error: Unexpectedly found nil while unwrapping an Optional value`
![screen shot 2018-03-12 at 21 11 20](https://user-images.githubusercontent.com/946680/37307046-f5ae9464-2639-11e8-9fd3-88eee41670b7.png)

is there anyone else who encountered this ? :)

thanks!

**Comment by lazaronixon** [comment]
Thank you.. I will fix it soon as possible

**Comment by lazaronixon** [comment]
Fixed https://github.com/lazaronixon/react-native-turbolinks/releases/tag/v1.2.7
