### ISSUE TITLE
Turbolinks for XCode 12.5.1

### ISSUE THREAD

**Issue by lanke96** [lazaronixon/react-native-turbolinks#87]
Hi there!

Are you planning to upload an update for XCode 12.5.1? It shows the following message:
![image](https://user-images.githubusercontent.com/18342337/125681197-45370ee3-cd60-40ab-b113-7bb7ec65bb4a.png)

If not, is there a way I can compile it myself? I will start a new project and I plan to use turbolinks for react native, but I'm not sure if this repo will be soon deprecated, and you will focus more on react-native-turbo. 
The reason why I don't use turbo for React Native is that I cannot run it on Android so far I know.

**Comment by lazaronixon** [comment]
You can compile turbolinks-ios using carthage and replace the turbolinks.Framework in your project https://github.com/turbolinks/turbolinks-ios#installing-with-carthage

**Comment by lanke96** [comment]
Thank you so much for the quick response! I will try this.
