### ISSUE TITLE
visitTabBar problem

### ISSUE THREAD

**Issue by Bickson** [lazaronixon/react-native-turbolinks#9]
hi, how am I suppose to provide icon Image?

this doesn't seem to work
```
Turbolinks.visitTabBar([
      {  
        tabTitle: 'Home',
        tabIcon: require('./home.png'),
        title: 'Title',
        url: 'https://somelink.com'
      },
])
```

I also tried to add image in xcode and access it through `assets/home`

thanks?

**Comment by Bickson** [comment]
my bad, just reference the image in assets with `just-image-name`

**Comment by lazaronixon** [comment]
Any question I am here..

**Comment by Bickson** [comment]
@lazaronixon thank you for the support! how do I set the navigationbar actions icon to something else the three dots ?

**Comment by lazaronixon** [comment]
It is not possible for now... I didn't implemented it because is not possible set it on android.. Maybe in future..
